### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by olsch88**
These are some fixes for the German translation.
"Bekanntheit" is actually "Ansehen" in the german version of the game.
IFF can be translated with "Freund-Feind-Erkennung"
Also, I would suggest leaving the title of

### CODE REVIEW

**Review by jamesjonesphoenix — COMMENTED** [review]
Thanks for going through this!
The parts in brackets are comments unused by the game itself. They don't really need translation but I'm of course happy to incorporate them.

I took most station name strings straight from the 0001-L049 main X3 t file and then simply coloured the race name. So a few strings here are different to what Egosoft thinks it should be.  
Page 17 ID 3481 You've changed to **Paraniden Handelsdock** when the source string is **Paranid Handelsdock**. Similar with 3491.
Page 17 ID 3771 You've changed to **Piratenschiff** when the source string is **Piraten Schiff** with a space. Similar with 3781. 
Page 350017 ID 15321 You've changed to **\033RKorsaren\033X Haven** when the source string is **Herzogs Hafen**.

I am happy to change these as per your request, just want to confirm you want to differ from Egosoft's original strings. It's fine with me, God knows Egosoft get things wrong all the time - but if any other Germans come whinging about it I will point them your way, lol.

Also 3491 has a double space which is my fault, but feel free to fix that.

**Comment by olsch88** [comment]
Thanks for the comment. I would rather stay with the original Egosoft version and will change my file soon.

**Comment by olsch88** [comment]
Fixed it (I hope)

**Comment by jamesjonesphoenix** [comment]
Merging - nice work!

**Pull request merged**
